import { expenseDatePattern, expenseReadFields, expenseSortFields } from "./expense-contract.js";

const version = Object.freeze({ type: "string", const: "v1" });
const handle = Object.freeze({ type: "string", minLength: 1, maxLength: 512 });
const fields = Object.freeze({ type: "array", minItems: 1, maxItems: expenseReadFields.length, uniqueItems: true, items: Object.freeze({ type: "string", enum: expenseReadFields }) });
const date = Object.freeze({ type: "string", pattern: expenseDatePattern, description: "Inclusive expense calendar date, YYYY-MM-DD." });
const annotations = Object.freeze({ readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } as const);
const securitySchemes = Object.freeze([Object.freeze({ type: "oauth2", scopes: Object.freeze(["expenses.read"] as const) } as const)]);
const source = Object.freeze({ type: "object", required: Object.freeze(["provider", "view", "readCompletedAt", "materialization"]), properties: Object.freeze({
  provider: Object.freeze({ type: "string", const: "d1" }), view: Object.freeze({ type: "string", const: "persisted" }),
  readCompletedAt: Object.freeze({ type: "string", format: "date-time", description: "Read completion time, not a synchronization or snapshot guarantee." }),
  materialization: Object.freeze({ type: "object", required: Object.freeze(["performed", "status"]), properties: Object.freeze({ performed: Object.freeze({ type: "boolean", const: false }), status: Object.freeze({ type: "string", const: "not_evaluated" }) }) }),
}) });
const period = Object.freeze({ type: "object", required: Object.freeze(["kind", "startDate", "endDate", "startInclusive", "endInclusive"]), properties: Object.freeze({
  kind: Object.freeze({ type: "string", const: "calendar_dates" }),
  startDate: Object.freeze({ type: Object.freeze(["string", "null"]), pattern: expenseDatePattern }), endDate: Object.freeze({ type: Object.freeze(["string", "null"]), pattern: expenseDatePattern }),
  startInclusive: Object.freeze({ type: "boolean", const: true }), endInclusive: Object.freeze({ type: "boolean", const: true }),
}) });
const output = (list: boolean): Readonly<Record<string, unknown>> => Object.freeze({ type: "object", required: Object.freeze(["data", "meta"]), properties: Object.freeze({
  data: list ? Object.freeze({ type: "object", required: Object.freeze(["items", "total"]), properties: Object.freeze({
    items: Object.freeze({ type: "array", maxItems: 100, items: Object.freeze({ type: "object", required: Object.freeze(["id"]) }) }), total: Object.freeze({ type: "integer", minimum: 0 }),
  }) }) : Object.freeze({ type: "object", required: Object.freeze(["id"]) }),
  meta: Object.freeze({ type: "object", required: Object.freeze(["contract_version", "source", ...(list ? ["next_cursor", "period"] : [])]), properties: Object.freeze({
    contract_version: version, source, ...(list ? { period, next_cursor: Object.freeze({ type: Object.freeze(["string", "null"]), minLength: 32, maxLength: 128 }) } : {}),
  }) }),
}) });

/** Public descriptors for the canonical server's persisted-only expense tools. */
export const expenseMcpTools = Object.freeze([
  Object.freeze({ name: "bizyeet_expenses_list", title: "List expenses", description: "Read a bounded page of persisted expenses. Scheduled occurrences are not generated by this read; empty rows do not prove no expenses are due. Dates are inclusive calendar dates. Preserve currencies; notes require explicit field selection.", annotations, securitySchemes,
    inputSchema: Object.freeze({ type: "object", required: Object.freeze(["api_version"]), additionalProperties: false, properties: Object.freeze({ api_version: version, fields,
      page_size: Object.freeze({ type: "integer", minimum: 1, maximum: 100 }), cursor: Object.freeze({ type: "string", minLength: 32, maxLength: 128 }),
      search: Object.freeze({ type: "string", maxLength: 120 }), sort: Object.freeze({ type: "string", enum: expenseSortFields }),
      dir: Object.freeze({ type: "string", enum: Object.freeze(["asc", "desc"]) }), status: Object.freeze({ type: "string", enum: Object.freeze(["due", "paid", "skipped"]) }),
      category: Object.freeze({ type: "string", maxLength: 32 }), currency: Object.freeze({ type: "string", pattern: "^[A-Z]{3}$" }), schedule: handle, start_date: date, end_date: date,
    }) }), outputSchema: output(true),
  }),
  Object.freeze({ name: "bizyeet_expenses_get", title: "Get expense", description: "Read one persisted expense by its opaque tenant-bound ID. Schedule references are opaque IDs. Notes require explicit field selection; this does not generate recurring expenses.", annotations, securitySchemes,
    inputSchema: Object.freeze({ type: "object", required: Object.freeze(["api_version", "id"]), additionalProperties: false, properties: Object.freeze({ api_version: version, fields, id: handle }) }), outputSchema: output(false),
  }),
] as const);
